### ISSUE TITLE
lora workflow not loading

### ISSUE THREAD

**Issue by agustincaniglia** [XLabs-AI/x-flux-comfyui#14]
lora workflow does not load?

**Comment by Vovanm88** [comment]
what do you mean?

**Comment by JimmyTime** [comment]
Mine's not looking in the right place for Loras, it defaulted to the furry one, but when I try to change it I have no options, meaning it's not looking at the 'normal' lora folder

**Comment by marafribus** [comment]
You shoul put Flux Loras to models\xlabs\loras
