### ISSUE TITLE
x-flux-comfyui install failed: With the current security level configuration, only custom nodes from the "default channel" can be installed.

### ISSUE THREAD

**Issue by wxuefei** [XLabs-AI/x-flux-comfyui#16]
Hi all ! 
How to solve this issue?

**Comment by Vovanm88** [comment]
Try this
https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-this-action-is-not-allowed-with-this-security-level-configuration

**Comment by wxuefei** [comment]
> Try this https://comfyui-guides.runcomfy.com/ultimate-comfyui-how-tos-a-runcomfy-guide/how-to-fix-this-action-is-not-allowed-with-this-security-level-configuration

Thanks very much! It's solved!  

modify custom_nodes\ComfyUI-Manager\config.ini and change security_level to:
security_level = weak
