### ISSUE TITLE
'ControlNetFlux' object has no attribute 'load_device'

### ISSUE THREAD

**Issue by barakyo** [XLabs-AI/x-flux-comfyui#17]
## Background

Ran into this when trying the canny_workflow.json using either `flux-canny-controlnet_v2.safetensors` or `flux-canny-controlnet.safetensors`. I didn't make any changes to the workflow.

I've also made sure my [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux) is up to date.

My `models/xlabs` looks like this:

```
xlabs/
├── controlnets
│   └── flux-canny-controlnet_v2.safetensors
├── flux
│   └── flux-dev.safetensors
└── loras
```

I copied my `flux-dev` model into the `xlabs/flux` folder just in case, but that didn't have any effect.

## Error
```
Error occurred when executing XlabsSampler:

'ControlNetFlux' object has no attribute 'load_device'

File "/home/user/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 333, in sampling
mm.load_models_gpu([model,controlnet])
File "/home/user/ComfyUI/comfy/model_management.py", line 399, in load_models_gpu
loaded_model = LoadedModel(x)
^^^^^^^^^^^^^^
File "/home/user/ComfyUI/comfy/model_management.py", line 268, in __init__
self.device = model.load_device
^^^^^^^^^^^^^^^^^
File "/home/user/miniconda3/envs/comfyenv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
```

Let me know if you need more info

**Comment by barakyo** [comment]
Looks like it comes from this commit: https://github.com/XLabs-AI/x-flux-comfyui/commit/73cc33e7e3874b48bba35357ad18b52fadec70ba#diff-e485eb8bfa77e53e217e9b400c67298309ef679c6ecd69a1174366f48bb93499R333

Commenting it out and restarting _seems_ to work. I don't get the error anymore, although I'm not sure what effect this has on the end result.

**Comment by NyxWeigh** [comment]
Exactly the same problem here, can't be resolved by the commenting method, hope there will be a real solution or update

**Comment by barakyo** [comment]
Looks like this was fixed in the [latest commits.](https://github.com/XLabs-AI/x-flux-comfyui/commit/90379ce521f4f468031b9f972ba5023f2d4cd7ed) I just reverted my change and pulled latest from main and it worked.
