### ISSUE TITLE
ComfyUI Workflow - Not Working (missing node types)

### ISSUE THREAD

**Issue by agahEbrahimi** [XLabs-AI/x-flux-comfyui#28]
When I drag and drop _[flux-controlnet-canny-v3-workflow.json](https://github.com/XLabs-AI/x-flux-comfyui/blob/main/workflows/flux-controlnet-canny-v3-workflow.json)_ after installing the custom_node, it throws the below error. 

```
Warning: Missing Node Types When loading the graph, the following node types were not found:
CannyEdgePreprocessor
Nodes that have failed to load will show as red on the graph.
```

<img width="1613" alt="Screenshot 2024-08-16 at 4 00 46 PM" src="https://github.com/user-attachments/assets/f6fc6ad0-6ada-4e02-be08-f4cb8df2fdd7">

Steps to reproduce:
- Clone ComfyUI.
- Follow custom_node instructions on the flux-comfyui README.
- Start ComfyUI & Paste the workflow json into the interface.

**Comment by 100xlongx** [comment]
did you install this? its in the manager as well

https://github.com/Fannovel16/comfyui_controlnet_aux

**Comment by agahEbrahimi** [comment]
That fixed it! A small clarification might be nice on the ReadMe that tells the user that python 3.10 and lower isn't supported because of package mismatches, otherwise thank you for pointing me in the right direction.
