### ISSUE TITLE
Required input is missing

### ISSUE THREAD

**Issue by 2575044704** [XLabs-AI/x-flux-comfyui#32]
### I downloaded flux-dev model and put it into ComfyUI/models/checkpoint, but I can't select the model
![image](https://github.com/user-attachments/assets/a1a1e4af-8b95-4ebd-851a-9a9c1af83d0c)

**Comment by Vovanm88** [comment]
That's because flux should go to "models/unet" in comfy

**Comment by 2575044704** [comment]
> That's because flux should go to "models/unet" in comfy

solved, and where can I find the two CLIP models?

**Comment by Vovanm88** [comment]
follow tutorial:
https://comfyanonymous.github.io/ComfyUI_examples/flux/

https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main
