### ISSUE TITLE
very confusing installation

### ISSUE THREAD

**Issue by lunatico67** [XLabs-AI/x-flux-comfyui#35]
It would be interesting to make a video explaining the installation or to explain in more detail for those of us who are not computer scientists.
Custom nodes are usually installed either through the custom nodes manager or with git clone.
Your process says: 
Clone this repo, path should be ComfyUI/custom_nodes/x-flux-comfyui/*, where * is all the files in this repo.
Then, it would be to create a folder in custom nodes called x-flux-comfyui and apply in that folder: git clone https://github.com/XLabs-AI/x-flux-comfyui.git ?
where * is all the files in this repo.  
which are all the files in this repo?

**Comment by AI-Made-Simple** [comment]
should just say , install via manager, then place lora in ComfyUI\models\xlabs\loras and controlnets in ComfyUI\models\xlabs\controlnets

**Comment by Vovanm88** [comment]
just install everything with use of comfyui nodes manager

**Comment by lunatico67** [comment]
thank you both very much, I will do so.

**Comment by sipie800** [comment]
+1
