### ISSUE TITLE
Which directory the controlnet model should be placed under

### ISSUE THREAD

**Issue by wuqq** [XLabs-AI/x-flux-comfyui#50]
Canny: flux-canny-controlnet-v3.safetensors
Depth: flux-depth-controlnet-v3.safetensors
Hed: flux-hed-controlnet-v3.safetensors
Which directory should these models be placed under
（\ComfyUI\models\controlnet ）This directory does not work

**Comment by PrometheusDante** [comment]
`ComfyUI\models\xlabs\controlnets` works for me

**Comment by ApexArtist** [comment]
ComfyUI\models\xlabs\controlnets works for me for real ?

**Comment by PsypmP** [comment]
ComfyUI\models\xlabs\controlnets doesn't work for me
upd
What nonsense. Comfyui desktop has 2 folders "models"
