### ISSUE TITLE
Load Flux Lora throws an error with GGUF Flux Dev model Q4

### ISSUE THREAD

**Issue by Adinapunyo-Banerjee** [XLabs-AI/x-flux-comfyui#57]
I have taken the lora workflow, changed to Load Unet (GGUF) as I use the GGUF Flux Dev Q4_0 model. I added a lora to the xlabs/lora folder from Civitai, here's the link to the lora - https://civitai.com/models/121544/natalie-portman-sdxl-flux.

Dual Clips loaded are: clip_l.safetensors and t5xxl_fp8_e4m3fn.safetensors

**Here's a Screen Shot of the workflow:**

![image](https://github.com/user-attachments/assets/d06a2b3e-9078-4230-994a-8ab9dcc3eddb)

**Here's the error:**

model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
['Natalie Portman Flux (woman).safetensors']
['Natalie Portman Flux (woman).safetensors']
['Natalie Portman Flux (woman).safetensors']
['Natalie Portman Flux (woman).safetensors']
Is model already patched? False
!!! Exception during processing !!! list index out of range
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ComfyUI\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 117, in loadmodel
    checkpoint, lora_rank = load_flux_lora(os.path.join(dir_xlabs_loras, lora_name))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 59, in load_flux_lora
    a1 = sorted(list(checkpoint[list(checkpoint.keys())[0]].shape))[0]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Adinapunyo-Banerjee** [comment]
I tried to rename the lora so that there are no spaces in between, still doesn't solve the issue...

**Comment by PrometheusDante** [comment]
For some reason the Flux Lora loader only ever worked on one LoRA for me so far, which was _FaetasticDetails_. All others I had to use a regular LoRA loader for and they worked just fine. 
Using rgthree's power lora loader and had no issues so far. But I found that the _FaetasticDetails_ LoRA does nothing when used with that regular LoRA loader. So there seem to be some differences that make LoRAs only compatible/functional using one or the other.
Btw. LoRA have to be copied/moved over to the regular `ComfyUI\models\loras` folder to show up in the regular LoRA loaders' dropdown menus

**Comment by Adinapunyo-Banerjee** [comment]
> For some reason the Flux Lora loader only ever worked on one LoRA for me so far, which was _FaetasticDetails_. All others I had to use a regular LoRA loader for and they worked just fine. Using rgthree's power lora loader and had no issues so far. But I found that the _FaetasticDetails_ LoRA does nothing when used with that regular LoRA loader. So there seem to be some differences that make LoRAs only compatible/functional using one or the other. Btw. LoRA have to be copied/moved over to the regular `ComfyUI\models\loras` folder to show up in the regular LoRA loaders' dropdown menus

Could you please give me a workflow that works with Flux loras and the Flux Q4_0 GGUF Unet model? And what's with the rgthree's power lora loader?

I just wanna get to use the Loras from Civitai in my Quantized Flux Dev model locally...

**Comment by PrometheusDante** [comment]
@Adinapunyo-Banerjee Sure, here it is. The rgthree's node is in there as well. Make sure to update everything and you should be good to go.
https://civitai.com/models/643835/comfyui-flux-advanced?modelVersionId=743120
Going to update it very soon though to simplify it some more and get rid of the second xlabs sampler

**Comment by Adinapunyo-Banerjee** [comment]
@PrometheusDante This might be stupid, but I can't seem to get around with your workflow 😅.

Could you make me a simple workflow like mine? Where I could just load my Q4_0 model, its clips and a Flux lora from Civitai, and finally just save the image after one pass? Sorry, I'm just new to all of this. I had some experience with SDXL and Pony, but Flux seems so complicated lol

**Comment by PrometheusDante** [comment]
@Adinapunyo-Banerjee Oh, no worries. My workflows tend to get a little large with all the options and whatnot. But I am working on making it simpler 😁

For now I made you an extra minimal one that does not require any extra nodes aside from the ones you already have.
[minimal_flux.json](https://github.com/user-attachments/files/16683639/minimal_flux.json)
![minimal_flux](https://github.com/user-attachments/assets/11e1dd65-cdf1-473c-b1aa-2e9e81bcb1cc)

**Comment by qlxxkj** [comment]
![image](https://github.com/user-attachments/assets/2bd4b4b5-2a55-4b05-8539-b5efe4f6d51f)


Error occurred when executing FluxLoraLoader:

'Linear' object has no attribute 'out_features'

File "/home/hawk/sd/ComfyUI/execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/home/hawk/sd/ComfyUI/execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "/home/hawk/sd/ComfyUI/execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "/home/hawk/sd/ComfyUI/execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "/home/hawk/sd/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 132, in loadmodel
patches=FluxUpdateModules(tyanochky, pbar)
File "/home/hawk/sd/ComfyUI/custom_nodes/x-flux-comfyui/utils.py", line 81, in FluxUpdateModules
patches[f"double_blocks.{i}"]=CopyDSB(flux_model.diffusion_model.double_blocks[i])
File "/home/hawk/sd/ComfyUI/custom_nodes/x-flux-comfyui/utils.py", line 19, in CopyDSB
mlp_hidden_dim = tyan.img_mlp[0].out_features
File "/home/hawk/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

**Comment by Adinapunyo-Banerjee** [comment]
@PrometheusDante Nope, it still doesn't seem to work. This is what I get:
![image](https://github.com/user-attachments/assets/9f57a16d-a254-404f-828b-2e4caf492db4)

I don't think the lora is the problem either because I ran it on an Online service running the Fp8 dev version of Flux on fal.ai, it worked perfectly there!

I think loras from civitai are not meant to be used on quantized models yet...

And let's not talk about the generation speed either 😂 (I run on 4GB VRAM)

**Comment by Adinapunyo-Banerjee** [comment]
@PrometheusDante could you please check if the same lora works on the same workflow of yours? The trigger word is "woman".

**Comment by PrometheusDante** [comment]
@Adinapunyo-Banerjee alright, just tested it and it worked without issues on a quantized .gguf
![workflow](https://github.com/user-attachments/assets/c28e08e1-350a-43b1-9fc6-3f34a98277e9)
Testing `Load Flux Lora` however threw me a new different error I did not get with other LoRAs so far
![error](https://github.com/user-attachments/assets/32a53010-9afd-4057-a58b-696392f574bc)



Using flux with 4gb VRAM is really rough though. The uploader of another .gguf merge (https://civitai.com/models/657607?modelVersionId=747918) wrote this : 
_"[Current situation: Using Forge UI I can run Q8_0 on my 11GB 1080ti but on Comfy I can only go up to Q5_1. Hopefully this will improve in the future.]"_
So maybe Forge would at least allow you to run generations more efficiently as of now it seems.

**Comment by Adinapunyo-Banerjee** [comment]
@PrometheusDante don't worry about my VRAM, I'll get a new GPU or a online hosted solution soon. But the thing is, why is the lora not working on my current specs? Never mind the generation times. I noticed you used a Q4_1, and I used Q4_0. Does that have something to do with it? Or did I rename the lora with spaces in between? Also where did you get the VAE? Give me the link to the VAE and lemme change that and try again...

**Comment by corporate9601** [comment]
> @Adinapunyo-Banerjee alright, just tested it and it worked without issues on a quantized .gguf ![workflow](https://private-user-images.githubusercontent.com/101045677/359820766-c28e08e1-350a-43b1-9fc6-3f34a98277e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDI3NTEsIm5iZiI6MTcyNDM0MjQ1MSwicGF0aCI6Ii8xMDEwNDU2NzcvMzU5ODIwNzY2LWMyOGUwOGUxLTM1MGEtNDNiMS05ZmM2LTNmMzRhOTgyNzdlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxNjAwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWRlYTc0OTBjZjQ5MTczNjdjMzI0NjI2NWVkZDcwZGZkNDg0NGUwNjkxZWZiMWMxYzY3OTQwNzBlNDc2ZWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QiGynxdlczUG_U8F7Ydo69bLbPjo1hk82X44xuLWpO0) Testing `Load Flux Lora` however threw me a new different error I did not get with other LoRAs so far ![error](https://private-user-images.githubusercontent.com/101045677/359825208-32a53010-9afd-4057-a58b-696392f574bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNDI3NTEsIm5iZiI6MTcyNDM0MjQ1MSwicGF0aCI6Ii8xMDEwNDU2NzcvMzU5ODI1MjA4LTMyYTUzMDEwLTlhZmQtNDA1Ny1hNThiLTY5NjM5MmY1NzRiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxNjAwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTVmZmVmY2M3Mjg4MzM0NzY1NmZlMWM3MjQzMGQzNzQ1MDk5OGIyM2M0YmY2ZWVjM2IyNDExYjI5NDEzZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xchdQkyzzxsh-et6LOP01JdNmvrETjXPUxrxVWhnqXw)
> 
> Using flux with 4gb VRAM is really rough though. The uploader of another .gguf merge (https://civitai.com/models/657607?modelVersionId=747918) wrote this : _"[Current situation: Using Forge UI I can run Q8_0 on my 11GB 1080ti but on Comfy I can only go up to Q5_1. Hopefully this will improve in the future.]"_ So maybe Forge would at least allow you to run generations more efficiently as of now it seems.

I just trained my first LORA using Kohya ss and I'm getting the same error as you when trying to use it in comfyui! It works in the basic inference script that comes with kohya, but if using it in comfy I also get: 

"Error occurred when executing FluxLoraLoader:

list index out of range" like what a weird generic error. and I'm using full flux dev but I trained this lora with --split_mode 
--network_args "train_blocks=single" so maybe that's why

**Comment by hainguyen666** [comment]
![image](https://github.com/user-attachments/assets/2a985fc4-36bc-4ad0-99bf-b5460a90e723)
![image](https://github.com/user-attachments/assets/78c0b677-efd3-4ae1-af23-a7e2f3fb39de)
Does anyone have this error when using the adapter with the GGUF Q5 model?

**Comment by venetanji** [comment]
> ![image](https://private-user-images.githubusercontent.com/143708202/361140337-2a985fc4-36bc-4ad0-99bf-b5460a90e723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTUwMDUsIm5iZiI6MTcyNDUxNDcwNSwicGF0aCI6Ii8xNDM3MDgyMDIvMzYxMTQwMzM3LTJhOTg1ZmM0LTM2YmMtNGFkMC05OWJmLWI1NDYwYTkwZTcyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxNTUxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTgxNTMzMWQxYWM1ZTllNzdkNWY0N2VkYWRlMzg3YTg3NGE4OTg3OTBjZTIwOTQ2Zjk5YmIwODMxOGYwYzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DttJJFW759uk0VV85yRm-svJ0gjKWuJW71DX7qx5S1k) ![image](https://private-user-images.githubusercontent.com/143708202/361140392-78c0b677-efd3-4ae1-af23-a7e2f3fb39de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTUwMDUsIm5iZiI6MTcyNDUxNDcwNSwicGF0aCI6Ii8xNDM3MDgyMDIvMzYxMTQwMzkyLTc4YzBiNjc3LWVmZDMtNGFlMS1hZjIzLWE3ZTJmM2ZiMzlkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxNTUxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Njg2ZGUwNDQ2ZWVhYTYwMTBkNTZlOTQzYmQ2MGEzMDY4YTUyNDk0YjdkMmI5ZTI0YzViYzdhZjY4ZDU4Y2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NtbISnVRMrKK4sBxMJ-3yOuQix0c4QXSvdZzp09VLJk) Does anyone have this error when using the adapter with the GGUF Q5 model?

Yes I'm also getting this error! Not sure it's the same issue though. Maybe better to move this to its own thread.

**Comment by Slava-On** [comment]
@hainguyen666 

I am getting the same error thrown by Apply FluxIPAdapter.
I am running in ComfyUI GGUF model flux1-dev-Q4_1

**Comment by bleetube** [comment]
> ![image](https://private-user-images.githubusercontent.com/143708202/361140337-2a985fc4-36bc-4ad0-99bf-b5460a90e723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDk1NzYsIm5iZiI6MTcyNDcwOTI3NiwicGF0aCI6Ii8xNDM3MDgyMDIvMzYxMTQwMzM3LTJhOTg1ZmM0LTM2YmMtNGFkMC05OWJmLWI1NDYwYTkwZTcyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMTU0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGUxNGRhMDNlOWE2NjcyNDE0NmMzYWEzMmY2NmM2M2YyOWNiN2Y4ZWUzMGNjM2RlMGM0NTk3ZDc0NDllM2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pcwMAbqFaQ0h2f0OIk0vVRZkySg5pnWbII8o3gxxGzc) ![image](https://private-user-images.githubusercontent.com/143708202/361140392-78c0b677-efd3-4ae1-af23-a7e2f3fb39de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDk1NzYsIm5iZiI6MTcyNDcwOTI3NiwicGF0aCI6Ii8xNDM3MDgyMDIvMzYxMTQwMzkyLTc4YzBiNjc3LWVmZDMtNGFlMS1hZjIzLWE3ZTJmM2ZiMzlkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMTU0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTI5MjRmZWYyMjgyZGYzMzRkY2IzZDMxMjMxZjlkMDA3YjY3ZjllMDg1MjQxZTNjMjA1YWUxZTNiYzJlODRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gDk6PWzQmnCRIBrbeWHXH6cgcCkCqJUPrfiedFCtbLw) Does anyone have this error when using the adapter with the GGUF Q5 model?

> Linear' object has no attribute 'out_features'

There's an [issue on the GGUF model repo](https://github.com/city96/ComfyUI-GGUF/issues/62) about this error that says "GGUF Models aren't supported"

**Comment by Anghellia** [comment]
Hi, we added GGUF support recently in our nodels, please try again!

**Comment by Slava-On** [comment]
Hello. 

I reinstalled the custom node X-flux-comfyui.
If, previously it was LoadFluxIpAdapter node, that was throwing the error "Linear object has no attribute out_features", now it is a custom node ApplyFluxIPAdapter node, that throws the same error...

**Comment by Vovanm88** [comment]
fixed I think

**Comment by SPOOKEXE** [comment]
![image](https://github.com/user-attachments/assets/0b630db2-b4c2-4d65-b8c9-9787e0dc0a00)

Having the same issue here with the Lora loader.

**Comment by laochendeai** [comment]
> @Adinapunyo-Banerjee哦，不用担心。我的工作流程往往会因为各种选项和其他东西而变得有点庞大。但我正在努力让它变得更简单 😁
> 
> [现在我为你制作了一个额外的最小节点，](https://github.com/user-attachments/files/16683639/minimal_flux.json)除了你已经拥有的节点之外，它不需要任何额外的节点。 [](https://github.com/user-attachments/files/16683639/minimal_flux.json) ![最小通量](https://private-user-images.githubusercontent.com/101045677/359684390-11e1dd65-cdf1-473c-b1aa-2e9e81bcb1cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNTM0MjIsIm5iZiI6MTcyNjM1MzEyMiwicGF0aCI6Ii8xMDEwNDU2NzcvMzU5Njg0MzkwLTExZTFkZDY1LWNkZjEtNDczYy1iMWFhLTJlOWU4MWJjYjFjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQyMjMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmNmM2VmNDlmYWM1NDVhMDc4NDk0YzlmODUwNGIwOGE1OTRjN2I3YTcyNTU5Y2VkOGJkZTM2NGZlOWEwYzQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VSiFijXclo9roMeR0860Ql34Jhx4HyTigF3zi8NuOcs)

请问他能运行在8g显存吗？

**Comment by giusparsifal** [comment]
>Btw. LoRA have to be copied/moved over to the regular `ComfyUI\models\loras` folder to show up in the regular LoRA loaders' dropdown menus

Hello, exactly where? I found "Load Flux Lora" for the first time in a workflow (usually was always a loara loader) but it can't find any Lora and I don't know in what folder I have to put my Lora.
Thanks.

**Comment by laochendeai** [comment]
您的来信已经收到，我会尽快给您回复。
