### ISSUE TITLE
Is this necessary？Please do not locked torch versions in requirements.txt.  Many Users on different versions of pytorch.

### ISSUE THREAD

**Issue by Erwin11** [XLabs-AI/x-flux-comfyui#6]
I saw requirements.txt
GitPython
torch==2.4.0
torchvision==0.19.0

Please do not locked torch versions
Many Users on different versions of pytorch.

**Comment by Vovanm88** [comment]
kind of, optimum-quantize had required very specific version of torch and torchvison and pytorch had issue with new version of torch and torchvision, I will test soon and if it works fine remove

**Comment by nokai** [comment]
I did that, and now COMFYUI won't start.. How do I fix it?

**Comment by gradient-diffusion** [comment]
fixed

**Comment by gradient-diffusion** [comment]
try again

**Comment by Vovanm88** [comment]
fixed
