### ISSUE TITLE
Error in XlabsSampler processing

### ISSUE THREAD

**Issue by kaki373** [XLabs-AI/x-flux-comfyui#65]
I'm encountering the following error with XlabsSampler, which causes the process to stop:

AttributeError: 'DoubleStreamBlock' object has no attribute 'processor'

I'm running this in a venv, but it's not working correctly. Could someone with a working setup share their pip list? The requirements.txt file doesn't specify the versions.

![スクリーンショット 2024-08-21 200732](https://github.com/user-attachments/assets/09dec51e-cd64-492e-95a8-b0d831e73e4d)

**Comment by KINGLIFER** [comment]
I get list index out of range

**Comment by Vovanm88** [comment]
update please

**Comment by kaki373** [comment]
Thanks guys,although I'm not sure of the exact cause, I was able to get it working by pulling x-flux-comfyui along with several custom nodes
