### ISSUE TITLE
python setup.py error

### ISSUE THREAD

**Issue by guahunyo** [XLabs-AI/x-flux-comfyui#7]
![image](https://github.com/user-attachments/assets/56013107-38ad-4c0f-9bea-6fa72b454c56)

**Comment by Sasank-C** [comment]
getting the same error on windows, works fine on linux/WSL

**Comment by Vovanm88** [comment]
I will check this soon and try to fix, now try to install other parts of requirements manually and say please if works (or don't)

**Comment by guahunyo** [comment]
> I will check this soon and try to fix, now try to install other parts of requirements manually and say please if works (or don't)我会尽快检查并尝试修复，现在尝试手动安装要求的其他部分，并说如果有效（或无效）

deepseed is not very Windows friendly

**Comment by gradient-diffusion** [comment]
try again

**Comment by kayselmecnun** [comment]
there are still problems with setup.py on windows.
![image](https://github.com/user-attachments/assets/7c1f8933-5eb6-4456-a916-914e6708417c)

**Comment by Vovanm88** [comment]
Now it absolutely shouldn't try to open x-flux, try to delte x-labs-comfy and clone it again please

**Comment by kayselmecnun** [comment]
Edit: I found the issue. My root folder for comfy was "Comfy UI" with space, but in the error it sees "UI" as root folder due to spacing issue. removing the space fixed my problem

**Comment by Vovanm88** [comment]
fixed I belive
