### ISSUE TITLE
Console constantly reading the models content

### ISSUE THREAD

**Issue by tetsuoo-online** [XLabs-AI/x-flux-comfyui#86]
I mean, look :
![image](https://github.com/user-attachments/assets/048f098b-5c34-4670-aaeb-de4b13491fef)

I can't use this package because it makes reading the console impossible; whenever I install it, if the xlabs folder is empty I would get an infinite list of :
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
[ ]
You see what I mean ? Now that I started to add controlnet and whatnot, it gets worse indeed, please how can I fix this

**Comment by Vovanm88** [comment]
It should print this once you start generating for each node, will be deleted in next update, now be patient

**Comment by tetsuoo-online** [comment]
> It should print this once you start generating for each node, will be deleted in next update, now be patient

I think it's fixed now, thank you !

**Comment by wushangui** [comment]
HOW FIXED?
 I have the same problem,and I git the lastest plugin.

**Comment by Falkonar** [comment]
Not fixed yet

**Comment by YoungCoding** [comment]
> Not fixed yet



> HOW FIXED? I have the same problem,and I git the lastest plugin.

 https://github.com/XLabs-AI/x-flux-comfyui/issues/155#issuecomment-2745319861

**Comment by YoungCoding** [comment]
@Falkonar @wushangui 
Here  https://github.com/XLabs-AI/x-flux-comfyui/issues/155#issuecomment-2745319861
