### ISSUE TITLE
x-flux comfy node

### ISSUE THREAD

**Issue by Cal-DCosta** [XLabs-AI/x-flux-comfyui#96]
<img width="1187" alt="x-flux_error" src="https://github.com/user-attachments/assets/d72cf0f4-abcc-4e27-a5bd-df856d516dc1">

**Comment by Vovanm88** [comment]
Please show comfyui log after installing

**Comment by Cal-DCosta** [comment]
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 38, in <module>
    from .clip import FluxClipViT
![cal1](https://github.com/user-attachments/assets/b11d94fe-e41f-4188-9b54-849001846f8f)

  File "D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\clip.py", line 3, in <module>
  
  
  I-Manager\custom-node-list.json [DONE]
FETCH DATA from: https://github.com/ltdrdata/ComfyUI-Manager/raw/main/custom-node-list.json [DONE]
Install custom node 'ComfyUI CogVideoX Wrapper'
Install: ['https://github.com/kijai/ComfyUI-CogVideoXWrapper']
Download: git clone 'https://github.com/kijai/ComfyUI-CogVideoXWrapper'
[!]
100%|██████████| 14.0/14.0 [00:01<00:00, 12.73it/s]
100%|██████████| 14.0/14.0 [00:01<00:00, 12.73it/s]
100%|██████████| 6.0/6.0 [00:01<00:00,  5.45it/s]
100%|██████████| 6.0/6.0 [00:01<00:00,  5.45it/s]
100%|██████████| 193.0/193.0 [00:01<00:00, 172.63it/s]
100%|██████████| 193.0/193.0 [00:01<00:00, 172.63it/s]
100%|██████████| 113.0/113.0 [00:01<00:00, 100.81it/s]
100%|██████████| 113.0/113.0 [00:01<00:00, 100.72it/s]
100%|██████████| 113.0/113.0 [00:01<00:00, 79.26it/s]
Install: pip packages
Installation was successful.
After restarting ComfyUI, please refresh the browser.

Restarting... [Legacy Mode]


[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-30 00:32:07.821334
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI
** Log path: D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['D:\\AI\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'huggingface_hub']

## Execute install/(de)activation script for 'D:\AI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper'
 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
